package io.hearth.smtp;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.attribute.PosixFilePermission;
import java.security.KeyFactory;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.PrivateKey;
import java.security.PublicKey;
import java.security.interfaces.RSAPrivateCrtKey;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.RSAPublicKeySpec;
import java.util.Base64;
import java.util.EnumSet;

/**
 * The one key this server signs outgoing mail with, and the DNS record that publishes it.
 *
 * <b>One key, and the domain in the signature is the domain the message arrived for.</b> A key per
 * domain would be the general answer; at one person with a handful of domains it is several files
 * to keep, several to back up, and several to forget when a new domain is added. The same public
 * key published at `&lt;selector&gt;._domainkey` on each domain says the same true thing on each of
 * them, and {@link #dnsRecord} prints the line to paste, once per domain.
 *
 * <b>2048 bits, because 1024 is refused by receivers and 4096 does not fit in one TXT string.</b>
 * A 4096-bit key has to be published as several quoted chunks, which every second DNS control panel
 * gets wrong, and the failure mode is a signature that verifies nowhere with no error anywhere.
 *
 * <b>It is a credential, so it lives in a file rather than the database</b> -- invariant 128, the
 * same rule that keeps `admin_emails` out of the admin section. Written 0600, and this refuses to
 * use a key that anybody else on the box can read: a DKIM key another account can read is a key that
 * signs mail in your name.
 */
public final class MailKeys {
  /** what receivers accept and what fits in one TXT string */
  public static final int KEY_BITS = 2048;

  private final PrivateKey privateKey;
  private final PublicKey publicKey;
  private final String selector;

  private MailKeys(PrivateKey privateKey, PublicKey publicKey, String selector) {
    this.privateKey = privateKey;
    this.publicKey = publicKey;
    this.selector = selector;
  }

  public PrivateKey privateKey() {
    return privateKey;
  }

  public String selector() {
    return selector;
  }

  /**
   * Load the key at a path, generating one if there is nothing there.
   *
   * Generating on first use rather than at install time is deliberate: the key is only needed the
   * first time a message is forwarded, and a server that cannot forward yet has nothing to sign.
   * What it must never do is generate a *second* key silently, because that would invalidate the
   * DNS record somebody has already published -- so an unreadable file is an error rather than a
   * reason to make a new one.
   */
  public static MailKeys open(File file, String selector) throws java.io.IOException {
    if (file.getParentFile() != null) {
      file.getParentFile().mkdirs();
    }
    if (!file.isFile()) {
      generateInto(file);
    }
    refusePublicKeyFile(file);
    String pem = Files.readString(file.toPath(), StandardCharsets.UTF_8);
    try {
      byte[] der = decodePem(pem);
      PrivateKey loaded = KeyFactory.getInstance("RSA")
          .generatePrivate(new PKCS8EncodedKeySpec(der));
      if (!(loaded instanceof RSAPrivateCrtKey crt)) {
        throw new java.io.IOException(file + " is an RSA key this server cannot derive a public"
            + " half from; a PKCS#8 private key generated by this server is what belongs here");
      }
      PublicKey pub = KeyFactory.getInstance("RSA").generatePublic(
          new RSAPublicKeySpec(crt.getModulus(), crt.getPublicExponent()));
      return new MailKeys(loaded, pub, selector);
    } catch (java.io.IOException ex) {
      throw ex;
    } catch (Exception ex) {
      throw new java.io.IOException("the signing key at " + file + " could not be read: "
          + ex.getMessage(), ex);
    }
  }

  private static void generateInto(File file) throws java.io.IOException {
    try {
      KeyPairGenerator generator = KeyPairGenerator.getInstance("RSA");
      generator.initialize(KEY_BITS);
      KeyPair pair = generator.generateKeyPair();
      String pem = "-----BEGIN PRIVATE KEY-----\n"
          + Base64.getMimeEncoder(64, new byte[]{'\n'}).encodeToString(pair.getPrivate().getEncoded())
          + "\n-----END PRIVATE KEY-----\n";
      Files.writeString(file.toPath(), pem, StandardCharsets.UTF_8);
    } catch (Exception ex) {
      throw new java.io.IOException("could not generate a signing key at " + file, ex);
    }
    tighten(file);
  }

  /**
   * Refuse a key anybody else on the machine can read.
   *
   * A DKIM private key is the ability to sign mail as this domain. Leaving it group- or
   * world-readable is the same class of mistake as a world-readable ssh key, and the reason to
   * refuse rather than to fix it silently is that a file with the wrong mode has usually been
   * copied from somewhere, and the copy it came from is the thing that needs looking at.
   */
  private static void refusePublicKeyFile(File file) throws java.io.IOException {
    try {
      var permissions = Files.getPosixFilePermissions(file.toPath());
      var loose = EnumSet.of(PosixFilePermission.GROUP_READ, PosixFilePermission.GROUP_WRITE,
          PosixFilePermission.OTHERS_READ, PosixFilePermission.OTHERS_WRITE);
      loose.retainAll(permissions);
      if (!loose.isEmpty()) {
        throw new java.io.IOException(file + " can be read by somebody other than its owner, and it"
            + " signs mail in your name. chmod 600 it, or generate a new one and republish the DNS"
            + " record.");
      }
    } catch (UnsupportedOperationException ex) {
      // a filesystem with no POSIX modes; nothing to check and nothing to complain about
    }
  }

  private static void tighten(File file) {
    try {
      Files.setPosixFilePermissions(file.toPath(),
          EnumSet.of(PosixFilePermission.OWNER_READ, PosixFilePermission.OWNER_WRITE));
    } catch (Exception ex) {
      // best effort: on a filesystem without modes there is nothing to set
    }
  }

  static byte[] decodePem(String pem) {
    StringBuilder base64 = new StringBuilder();
    for (String line : pem.split("\r?\n")) {
      String trimmed = line.trim();
      if (trimmed.isEmpty() || trimmed.startsWith("-----")) {
        continue;
      }
      base64.append(trimmed);
    }
    return Base64.getDecoder().decode(base64.toString());
  }

  /**
   * The TXT record to publish, as one line.
   *
   * `v=DKIM1; k=rsa; p=&lt;base64 of the SubjectPublicKeyInfo&gt;`. What people get wrong here is
   * pasting the PEM with its header lines and newlines intact, so this hands back exactly the
   * string and nothing around it.
   */
  public String dnsRecord() {
    return "v=DKIM1; k=rsa; p=" + Base64.getEncoder().encodeToString(publicKey.getEncoded());
  }

  /** where the record goes, for a given domain */
  public String dnsName(String domain) {
    return selector + "._domainkey." + domain;
  }
}
