package io.hearth.store;

/**
 * One column, as the code declares it.
 *
 * Ordering matters here. When a new column shows up in a release, the upgrader inserts it at the
 * position the code says it belongs rather than tacking it on the end, so that a database created
 * fresh today and a database upgraded through three releases have the same shape. That makes
 * "SELECT *", a schema dump, and a bug report all mean the same thing on every install.
 */
public class Column {
  public final String name;
  public final String type;
  public final boolean nullable;
  public final String defaultValue;
  public final boolean primaryKey;
  public final boolean autoIncrement;
  public final boolean unique;
  /** what this column used to be called, or null; see {@link #renamedFrom} */
  public final String was;

  private Column(String name, String type, boolean nullable, String defaultValue, boolean primaryKey, boolean autoIncrement, boolean unique) {
    this(name, type, nullable, defaultValue, primaryKey, autoIncrement, unique, null);
  }

  private Column(String name, String type, boolean nullable, String defaultValue,
                 boolean primaryKey, boolean autoIncrement, boolean unique, String was) {
    this.name = name;
    this.type = type;
    this.nullable = nullable;
    this.defaultValue = defaultValue;
    this.primaryKey = primaryKey;
    this.autoIncrement = autoIncrement;
    this.unique = unique;
    this.was = was;
  }

  public static Column id(String name) {
    return new Column(name, "BIGINT", false, null, true, true, false);
  }

  public static Column of(String name, String type) {
    return new Column(name, type, true, null, false, false, false);
  }

  public Column notNull() {
    return new Column(name, type, false, defaultValue, primaryKey, autoIncrement, unique, was);
  }

  public Column withDefault(String value) {
    return new Column(name, type, nullable, value, primaryKey, autoIncrement, unique, was);
  }

  public Column unique() {
    return new Column(name, type, nullable, defaultValue, primaryKey, autoIncrement, true, was);
  }

  /**
   * This column used to be called something else, and a database on disk may still call it that.
   *
   * <b>A name that has stopped being true is a bug with a long fuse.</b> `comments.post_id` held the
   * id of a post, then of a post or an event or a place, and the comment above it grew a paragraph
   * explaining that it does not mean what it says -- which is the point at which the next person
   * reads the name and not the paragraph. The upgrader could not help: it added and never renamed,
   * so the choice was a lie in the schema or a rewrite of every row.
   *
   * So a rename is declared here and the upgrader performs it, once, before it looks for anything
   * missing. It is the only name-changing thing it will do, and no value moves: H2's
   * `ALTER TABLE ... ALTER COLUMN ... RENAME TO` leaves the data exactly where it is. The
   * declaration is also the history, in the one place somebody reading the schema will see it.
   */
  public Column renamedFrom(String oldName) {
    return new Column(name, type, nullable, defaultValue, primaryKey, autoIncrement, unique,
        oldName);
  }

  /** the column definition as it appears inside CREATE TABLE */
  public String ddl() {
    StringBuilder sb = new StringBuilder();
    sb.append(name).append(' ').append(type);
    if (autoIncrement) {
      sb.append(" GENERATED BY DEFAULT AS IDENTITY");
    }
    if (!nullable) {
      sb.append(" NOT NULL");
    }
    if (defaultValue != null) {
      sb.append(" DEFAULT ").append(defaultValue);
    }
    if (primaryKey) {
      sb.append(" PRIMARY KEY");
    }
    return sb.toString();
  }

  /**
   * The definition used when adding this column to a table that already has rows.
   *
   * A NOT NULL column cannot be added to a populated table without a default, so one is required
   * at declaration time. The alternative -- silently relaxing it to nullable -- would mean a fresh
   * database and an upgraded one disagree about what is allowed, which is exactly the drift this
   * whole mechanism exists to prevent.
   */
  public String alterDdl() throws SchemaException {
    if (!nullable && defaultValue == null && !autoIncrement) {
      throw new SchemaException("column '" + name + "' is NOT NULL with no default, so it cannot be added"
          + " to an existing table; give it a default in the schema");
    }
    return ddl();
  }

  /** H2 reports types in its own spelling; compare on a normalized form */
  public String normalizedType() {
    return normalizeType(type);
  }

  static String normalizeType(String raw) {
    String type = raw.toUpperCase(java.util.Locale.ROOT).replace(" ", "");
    // H2 stores these under their canonical names
    if (type.startsWith("VARCHAR")) {
      return type.replace("CHARACTERVARYING", "VARCHAR");
    }
    if (type.equals("CHARACTERVARYING") || type.startsWith("CHARACTERVARYING(")) {
      return type.replace("CHARACTERVARYING", "VARCHAR");
    }
    if (type.equals("BOOL")) {
      return "BOOLEAN";
    }
    if (type.equals("INT") || type.equals("INTEGER")) {
      return "INTEGER";
    }
    if (type.equals("INT8")) {
      return "BIGINT";
    }
    if (type.startsWith("TIMESTAMP")) {
      return "TIMESTAMP";
    }
    return type;
  }

  @Override
  public String toString() {
    return name + " " + type;
  }
}
