package io.hearth.store;

/**
 * H2 in MODE=STRICT.
 *
 * Strict mode is deliberate: it refuses H2's own extensions, so SQL written against it is much more
 * likely to work unchanged on MySQL or PostgreSQL later. The cost is that a few conveniences are
 * unavailable -- LIMIT is the one that bites -- and those live here.
 */
public class H2Dialect implements Dialect {
  @Override
  public String name() {
    return "h2";
  }

  @Override
  public String identityColumn() {
    return "BIGINT GENERATED BY DEFAULT AS IDENTITY";
  }

  @Override
  public String limit(int rows) {
    return "FETCH FIRST " + rows + " ROWS ONLY";
  }

  @Override
  public String upsert(String table, String[] columns, String[] keyColumns) {
    StringBuilder sb = new StringBuilder("MERGE INTO ").append(table).append(" (");
    sb.append(String.join(", ", columns)).append(") KEY (");
    sb.append(String.join(", ", keyColumns)).append(") VALUES (");
    for (int k = 0; k < columns.length; k++) {
      sb.append(k > 0 ? ", ?" : "?");
    }
    return sb.append(')').toString();
  }

  @Override
  public boolean supportsColumnPositioning() {
    return true;
  }

  @Override
  public String schemaName() {
    return "PUBLIC";
  }

  @Override
  public String longTextType() {
    return "VARCHAR(1048576)";
  }
}
