package io.hearth.store;

import io.hearth.common.Verbose;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import java.io.File;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

/**
 * The self-upgrade, tested against a real H2 file.
 *
 * The interesting cases all involve a database that was created by an older version of the code, so
 * these tests build one by hand -- dropping columns out of the CREATE TABLE -- and then let the
 * upgrader put them back. That is the only way to prove the ordering guarantee, which is the whole
 * reason this mechanism exists rather than a plain "ADD COLUMN at the end".
 */
public class SchemaUpgraderTests {
  private File dir;
  private File file;

  @Before
  public void setUp() throws Exception {
    dir = Files.createTempDirectory("hearth-schema-test").toFile();
    file = new File(dir, "test.db");
  }

  @After
  public void tearDown() {
    File[] children = dir.listFiles();
    if (children != null) {
      for (File child : children) {
        child.delete();
      }
    }
    dir.delete();
  }

  private Connection connect() throws SQLException {
    return DriverManager.getConnection("jdbc:h2:" + file.getAbsolutePath() + ";MODE=STRICT", "sa", "");
  }

  private void run(String sql) throws SQLException {
    try (Connection connection = connect(); Statement statement = connection.createStatement()) {
      statement.execute(sql);
    }
  }

  private void upgrade() throws Exception {
    try (Connection connection = connect()) {
      new SchemaUpgrader(Verbose.OFF).upgrade(connection, "test");
    }
  }

  /** column names of a table, in the order the database has them */
  private List<String> columnOrder(String table) throws Exception {
    ArrayList<String> names = new ArrayList<>();
    try (Connection connection = connect();
         Statement statement = connection.createStatement();
         ResultSet rows = statement.executeQuery(
             "SELECT column_name FROM information_schema.columns WHERE table_schema = 'PUBLIC'"
                 + " AND table_name = '" + table.toUpperCase(Locale.ROOT) + "' ORDER BY ordinal_position")) {
      while (rows.next()) {
        names.add(rows.getString(1).toLowerCase(Locale.ROOT));
      }
    }
    return names;
  }

  private static List<String> declaredOrder(Table table) {
    return table.columns.stream().map(column -> column.name).toList();
  }

  // ---- renaming ------------------------------------------------------------------------------




  // ---- creating from nothing ---------------------------------------------------------------

  @Test
  public void anEmptyDatabaseGetsEveryTable() throws Exception {
    upgrade();
    assertEquals(declaredOrder(Schema.EMAILS_TABLE), columnOrder(Schema.EMAILS));
    assertEquals(declaredOrder(Schema.SESSIONS_TABLE), columnOrder(Schema.SESSIONS));
    assertEquals(declaredOrder(Schema.META_TABLE), columnOrder(Schema.META));
  }

  @Test
  public void h2OwnSessionsViewDoesNotLookLikeOurTable() throws Exception {
    // H2 ships INFORMATION_SCHEMA.SESSIONS; an unscoped metadata lookup finds it and the upgrader
    // then tries to ALTER a table that was never created
    upgrade();
    assertEquals(declaredOrder(Schema.SESSIONS_TABLE), columnOrder(Schema.SESSIONS));
  }

  @Test
  public void upgradingTwiceChangesNothing() throws Exception {
    upgrade();
    try (Connection connection = connect()) {
      SchemaUpgrader second = new SchemaUpgrader(Verbose.OFF);
      second.upgrade(connection, "test");
      assertTrue("a current database should need no DDL, got: " + second.applied(), second.applied().isEmpty());
      assertTrue(second.notes().isEmpty());
    }
  }

  @Test
  public void theVersionIsRecorded() throws Exception {
    upgrade();
    try (Connection connection = connect()) {
      assertEquals(Integer.toString(Schema.VERSION), SchemaUpgrader.storedVersion(connection));
    }
  }

  // ---- adding columns in the right place ---------------------------------------------------

  @Test
  public void aColumnMissingFromTheMiddleIsPutBackInPlace() throws Exception {
    // an older release without sessions_valid_after, which sits between last_login_at and
    // failed_attempts; a naive ADD COLUMN would put it on the end
    run("CREATE TABLE emails ("
        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,"
        + "email VARCHAR(320) NOT NULL,"
        + "password_hash VARCHAR(512),"
        + "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "verified_at TIMESTAMP,"
        + "last_login_at TIMESTAMP,"
        + "failed_attempts INTEGER NOT NULL DEFAULT 0,"
        + "locked_until TIMESTAMP,"
        + "disabled BOOLEAN NOT NULL DEFAULT FALSE)");
    upgrade();
    assertEquals("the upgraded table should be shaped exactly like a fresh one",
        declaredOrder(Schema.EMAILS_TABLE), columnOrder(Schema.EMAILS));
  }

  @Test
  public void severalMissingColumnsInARowLandInOrder() throws Exception {
    // three consecutive columns absent; each has to anchor against something that exists
    run("CREATE TABLE emails ("
        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,"
        + "email VARCHAR(320) NOT NULL,"
        + "password_hash VARCHAR(512),"
        + "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "failed_attempts INTEGER NOT NULL DEFAULT 0,"
        + "locked_until TIMESTAMP,"
        + "disabled BOOLEAN NOT NULL DEFAULT FALSE)");
    upgrade();
    assertEquals(declaredOrder(Schema.EMAILS_TABLE), columnOrder(Schema.EMAILS));
  }

  @Test
  public void aColumnMissingFromTheEndIsAppended() throws Exception {
    run("CREATE TABLE sessions ("
        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,"
        + "token_hash VARCHAR(64) NOT NULL,"
        + "user_id BIGINT NOT NULL,"
        + "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "expires_at TIMESTAMP,"
        + "revoked_at TIMESTAMP,"
        + "ip VARCHAR(64))");
    upgrade();
    assertEquals(declaredOrder(Schema.SESSIONS_TABLE), columnOrder(Schema.SESSIONS));
  }

  @Test
  public void existingRowsSurviveAnUpgrade() throws Exception {
    run("CREATE TABLE emails ("
        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,"
        + "email VARCHAR(320) NOT NULL,"
        + "password_hash VARCHAR(512),"
        + "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "verified_at TIMESTAMP,"
        + "last_login_at TIMESTAMP,"
        + "failed_attempts INTEGER NOT NULL DEFAULT 0,"
        + "locked_until TIMESTAMP,"
        + "disabled BOOLEAN NOT NULL DEFAULT FALSE)");
    run("INSERT INTO emails (email) VALUES ('somebody@example.com')");
    upgrade();
    try (Connection connection = connect();
         Statement statement = connection.createStatement();
         ResultSet rows = statement.executeQuery("SELECT email, sessions_valid_after FROM emails")) {
      assertTrue(rows.next());
      assertEquals("somebody@example.com", rows.getString(1));
      // the new column exists and is null for the row that predates it
      assertEquals(null, rows.getTimestamp(2));
      assertFalse(rows.next());
    }
  }

  @Test
  public void theDdlIsReportedForTheAudit() throws Exception {
    run("CREATE TABLE sessions ("
        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,"
        + "token_hash VARCHAR(64) NOT NULL,"
        + "user_id BIGINT NOT NULL,"
        + "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "last_seen_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "expires_at TIMESTAMP,"
        + "revoked_at TIMESTAMP,"
        + "user_agent VARCHAR(256))");
    try (Connection connection = connect()) {
      SchemaUpgrader upgrader = new SchemaUpgrader(Verbose.OFF);
      upgrader.upgrade(connection, "test");
      String ddl = String.join("\n", upgrader.applied());
      assertTrue(ddl, ddl.contains("ALTER TABLE sessions ADD COLUMN ip VARCHAR(64) BEFORE user_agent"));
    }
  }

  // ---- what it refuses to do ---------------------------------------------------------------

  @Test
  public void anExtraColumnIsLeftAloneAndReported() throws Exception {
    upgrade();
    run("ALTER TABLE emails ADD COLUMN nickname VARCHAR(64)");
    try (Connection connection = connect()) {
      SchemaUpgrader upgrader = new SchemaUpgrader(Verbose.OFF);
      upgrader.upgrade(connection, "test");
      assertTrue(upgrader.applied().isEmpty());
      assertEquals(1, upgrader.notes().size());
      assertTrue(upgrader.notes().get(0).contains("nickname"));
    }
    // still there; we do not drop what we did not create
    assertTrue(columnOrder(Schema.EMAILS).contains("nickname"));
  }

  @Test
  public void aChangedTypeIsFatal() throws Exception {
    run("CREATE TABLE emails ("
        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,"
        + "email VARCHAR(64) NOT NULL)");
    try {
      upgrade();
      fail("expected a refusal");
    } catch (SchemaException ex) {
      assertTrue(ex.getMessage(), ex.getMessage().contains("emails.email"));
      assertTrue(ex.getMessage(), ex.getMessage().contains("will not change a column's type"));
    }
  }

  @Test
  public void aNotNullColumnWithoutADefaultIsRefusedAtDeclarationTime() {
    // this is a bug in Schema.java, caught before it can meet a populated table
    try {
      Column.of("late", "VARCHAR(10)").notNull().alterDdl();
      fail("expected a refusal");
    } catch (SchemaException ex) {
      assertTrue(ex.getMessage(), ex.getMessage().contains("NOT NULL with no default"));
    }
  }

  @Test
  public void addingANotNullColumnWithoutADefaultFailsWithAClearMessage() throws Exception {
    // a hand-edited or half-migrated database missing a founding column. There is no correct value
    // to backfill, so the refusal has to name the column rather than surfacing as raw SQL.
    run("CREATE TABLE emails ("
        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,"
        + "password_hash VARCHAR(512))");
    try {
      upgrade();
      fail("expected a refusal");
    } catch (SchemaException ex) {
      assertTrue(ex.getMessage(), ex.getMessage().contains("'email' is NOT NULL with no default"));
      assertTrue(ex.getMessage(), ex.getMessage().contains("give it a default in the schema"));
    }
  }

  @Test
  public void everyColumnAddedAfterTheFoundingSetIsAddable() throws Exception {
    // the founding columns of each table only ever appear inside CREATE TABLE; everything declared
    // after them has to survive being added to a populated table, or the schema stops upgrading
    for (Table table : Schema.TABLES) {
      for (Column column : table.columns) {
        if (FOUNDING.contains(table.name + "." + column.name)) {
          continue;
        }
        column.alterDdl();
      }
    }
  }

  /** NOT NULL, no default, present since the table was created; never added by ALTER */
  private static final List<String> FOUNDING = List.of(
      "config.name", "config.value_text",
      "emails.email", "sessions.token_hash", "sessions.user_id",
      "roles.user_id", "roles.role_name", "templates.name", "content.uri",
      "profiles.user_id", "answers.user_id", "bans.email", "oauth_clients.client_id",
      "content_versions.content_id", "content_versions.version",
      "invites.email", "invites.token",
      "posts.author_id", "comments.subject_id", "comments.author_id", "notifications.user_id",
      "notify_prefs.user_id", "rsvps.event_id", "rsvps.user_id", "role_defs.name", "push_subs.session_id", "push_subs.user_id",
      "push_subs.endpoint", "place_types.slug", "places.type_slug",
      "places.slug", "themes.scope", "legal.slug",
      "signals.subject_id", "signals.user_id", "system_templates.slug",
      "public_rsvps.event_id", "public_rsvps.email",
      "availability.user_id", "calendar_links.user_id", "calendar_links.url",
      "calendar_cache.user_id", "calendar_cache.url_hash",
      "polls.post_id", "polls.kind",
      "poll_options.poll_id", "poll_options.facet",
      "poll_votes.poll_id", "poll_votes.option_id", "poll_votes.facet", "poll_votes.user_id",
      "projects.name", "projects.slug",
      "task_defs.name", "task_defs.slug",
      "tasks.project_id", "tasks.title",
      "task_entries.user_id",
      // attachments has no NOT NULL column without a default; everything is addable
      "schema_meta.meta_key", "schema_meta.meta_value");

  @Test
  public void aVersionOneDatabaseUpgradesToVersionTwoInPlace() throws Exception {
    // exactly the shape shipped before approval and roles existed: no approved_at, no signup
    // columns in the middle of emails, and no roles table at all
    run("CREATE TABLE emails ("
        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,"
        + "email VARCHAR(320) NOT NULL,"
        + "password_hash VARCHAR(512),"
        + "created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "verified_at TIMESTAMP,"
        + "last_login_at TIMESTAMP,"
        + "sessions_valid_after TIMESTAMP,"
        + "failed_attempts INTEGER NOT NULL DEFAULT 0,"
        + "locked_until TIMESTAMP,"
        + "disabled BOOLEAN NOT NULL DEFAULT FALSE)");
    run("INSERT INTO emails (email, verified_at) VALUES ('early@example.com', CURRENT_TIMESTAMP)");
    upgrade();

    assertEquals("the upgraded table should be shaped exactly like a fresh one",
        declaredOrder(Schema.EMAILS_TABLE), columnOrder(Schema.EMAILS));
    assertEquals(declaredOrder(Schema.ROLES_TABLE), columnOrder(Schema.ROLES));
    try (Connection connection = connect();
         Statement statement = connection.createStatement();
         ResultSet rows = statement.executeQuery(
             "SELECT email, approved_at, signup_events FROM emails")) {
      assertTrue(rows.next());
      assertEquals("the row from before the upgrade survives", "early@example.com", rows.getString(1));
      assertEquals("and is unapproved, which is the safe reading of 'we did not ask'", null, rows.getTimestamp(2));
      assertEquals("with a default rather than a null", 0, rows.getInt(3));
    }
  }

  @Test
  public void aCompositeUniqueIsAddedToAnExistingTable() throws Exception {
    run("CREATE TABLE roles ("
        + "id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,"
        + "user_id BIGINT NOT NULL,"
        + "role_name VARCHAR(64) NOT NULL,"
        + "granted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,"
        + "granted_by BIGINT)");
    upgrade();
    run("INSERT INTO roles (user_id, role_name) VALUES (1, 'admin')");
    try {
      run("INSERT INTO roles (user_id, role_name) VALUES (1, 'admin')");
      fail("a second identical grant should be refused by the constraint");
    } catch (SQLException expected) {
      assertTrue(expected.getMessage(), expected.getMessage().toLowerCase(Locale.ROOT).contains("unique"));
    }
  }

  @Test
  public void indexesAreCreated() throws Exception {
    upgrade();
    try (Connection connection = connect();
         Statement statement = connection.createStatement();
         ResultSet rows = statement.executeQuery(
             "SELECT index_name FROM information_schema.indexes WHERE table_schema = 'PUBLIC'")) {
      ArrayList<String> names = new ArrayList<>();
      while (rows.next()) {
        names.add(rows.getString(1).toLowerCase(Locale.ROOT));
      }
      assertTrue(names.toString(), names.contains("idx_sessions_user"));
      assertTrue(names.toString(), names.contains("idx_emails_email"));
    }
  }

  @Test
  public void aStoreOpensAuditsAndReports() throws Exception {
    try (Store store = Store.open(dir, "example.com", Verbose.OFF)) {
      assertNotNull(store.audit());
      assertFalse(store.audit().existed());
      assertTrue(store.audit().changed());
      assertEquals("created, schema v" + Schema.VERSION, store.audit().summary());
    }
    try (Store store = Store.open(dir, "example.com", Verbose.OFF)) {
      assertTrue(store.audit().existed());
      assertFalse(store.audit().changed());
      assertTrue(store.audit().summary().contains("already current"));
    }
  }
}
