package io.hearth.attach;

import io.hearth.auth.Accounts;
import io.hearth.store.Schema;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Which uploads is anything still pointing at?
 *
 * <b>Mark and sweep, and the marking is the part worth getting right.</b> A sweep that misses one
 * place a url can hide deletes a photograph that is on a page, which is a mistake nobody discovers
 * until somebody opens that page months later and finds a broken image with no way to work out what
 * was there. So this reads *every* column in this database that holds text somebody wrote, names
 * each of them on the screen, and refuses to offer anything for deletion if any of those reads
 * failed. Three tables would have covered the obvious cases; the ones that are not obvious are
 * exactly the ones that would bite.
 *
 * <b>Two of the sources are not obvious and both matter.</b> A page's *history* can reference an
 * attachment that the current version no longer does -- deleting it would make restoring that
 * version produce a broken page, and a history that cannot be restored is not a history. A
 * *suggested edit* waiting in the queue is the same problem before the fact. Both are scanned.
 *
 * <b>Nothing recent is ever offered.</b> A file uploaded twenty minutes ago is very likely sitting
 * on somebody's clipboard, or in a draft in another tab, on its way into a page that does not exist
 * yet. The grace period is what makes "delete everything unreferenced" a safe button rather than a
 * race against whoever is writing.
 *
 * <b>It finds urls, not intentions.</b> The regex matches the address these are served at, which is
 * what the editor inserts and what anybody writing markdown by hand would type. An operator who has
 * built a url out of string concatenation inside a template has written something this cannot see,
 * and the screen says so rather than pretending otherwise.
 */
public final class AttachmentSweep {
  /**
   * The address an attachment is served at, wherever it appears.
   *
   * Deliberately loose about what surrounds it -- markdown, an `<img src>`, an `<a href>`, a JSON
   * blob of template fields -- and strict about the shape, because that shape is generated by this
   * server and is the only thing a link can be.
   */
  private static final Pattern REFERENCE =
      Pattern.compile("/attachment/(\\d{1,18})\\.[A-Za-z0-9]{1,8}");
  /** how young is too young to be called rubbish */
  public static final Duration GRACE = Duration.ofHours(24);
  /** the most rows one source contributes; the scale target is a design input */
  private static final int CEILING = 20_000;

  private AttachmentSweep() {
  }

  /** one place a file is pointed at, in words a person can act on */
  public record Use(long attachmentId, String source, String where) {
  }

  /** what one scan found */
  public record Result(Set<Long> referenced, List<Use> uses, List<Attachments.Attachment> unused,
                       List<String> sources, List<String> problems, int rowsRead, long freeable,
                       Instant at) {
    public boolean trustworthy() {
      return problems.isEmpty();
    }

    /** everywhere one attachment is pointed at */
    public List<Use> usesOf(long id) {
      ArrayList<Use> found = new ArrayList<>();
      for (Use use : uses) {
        if (use.attachmentId() == id) {
          found.add(use);
        }
      }
      return found;
    }
  }

  /** every column this looks in, as a source name and the SQL that reads it */
  private record Source(String name, String describe, String sql) {
  }

  private static List<Source> sourcesOf() {
    ArrayList<Source> sources = new ArrayList<>();
    sources.add(new Source("pages", "the body, the title and the template fields of every page",
        "SELECT id, uri, body, fields, title FROM " + Schema.CONTENT));
    sources.add(new Source("page history",
        "every version of every page, because restoring one has to still work",
        "SELECT id, CAST(content_id AS VARCHAR), payload, summary FROM "
            + Schema.CONTENT_VERSIONS));
    sources.add(new Source("templates", "what an operator wrote around the pages",
        "SELECT id, name, body, parameters FROM " + Schema.TEMPLATES));
    sources.add(new Source("profiles", "what members wrote about themselves",
        "SELECT id, display_name, about, links FROM " + Schema.PROFILES));
    sources.add(new Source("legal", "the terms and the privacy policy, when a community wrote its own",
        "SELECT id, slug, body FROM " + Schema.LEGAL));
    sources.add(new Source("messages", "the wording of every email this community changed",
        "SELECT id, slug, subject, lead, body FROM " + Schema.SYSTEM_TEMPLATES));
    sources.add(new Source("file descriptions", "one attachment pointing at another",
        "SELECT id, filename, description FROM " + Schema.ATTACHMENTS));
    return sources;
  }

  /** every source this scan looks in, for the screen to list whether or not it has been run */
  public static List<String> describeSources() {
    ArrayList<String> described = new ArrayList<>();
    for (Source source : sourcesOf()) {
      described.add(source.name() + " -- " + source.describe());
    }
    return described;
  }

  public static Result run(Accounts accounts) throws SQLException {
    return run(accounts, GRACE, Instant.now());
  }

  /**
   * Read everything, then subtract.
   *
   * @param grace how young an upload has to be to be left alone whatever the scan says
   * @param now taken as a parameter so a test can be about the grace period rather than about
   *     waiting a day
   */
  public static Result run(Accounts accounts, Duration grace, Instant now) throws SQLException {
    LinkedHashSet<Long> referenced = new LinkedHashSet<>();
    ArrayList<Use> uses = new ArrayList<>();
    ArrayList<String> sources = new ArrayList<>();
    ArrayList<String> problems = new ArrayList<>();
    int rows = 0;

    for (Source source : sourcesOf()) {
      sources.add(source.name());
      try (Connection connection = accounts.store.connection();
           PreparedStatement statement = connection.prepareStatement(source.sql());
           ResultSet found = statement.executeQuery()) {
        int columns = found.getMetaData().getColumnCount();
        int read = 0;
        while (found.next() && read++ < CEILING) {
          rows++;
          // the first two columns are the row's id and something to call it; the rest is text
          String label = columns >= 2 ? found.getString(2) : null;
          for (int column = 3; column <= columns; column++) {
            mark(found.getString(column), source.name(),
                label == null || label.isBlank() ? "#" + found.getString(1) : label,
                referenced, uses);
          }
          // the second column is frequently a title, which can itself hold a link
          if (columns >= 2) {
            mark(label, source.name(), "#" + found.getString(1), referenced, uses);
          }
        }
      } catch (SQLException ex) {
        // A source that could not be read is the whole reason `trustworthy` exists. Carrying on
        // and offering a delete button would be offering to delete files this scan never looked
        // for -- so the scan finishes, says which source failed, and the button is not drawn.
        problems.add(source.name() + " could not be read: " + ex.getMessage());
      }
    }

    ArrayList<Attachments.Attachment> unused = new ArrayList<>();
    long freeable = 0;
    long youngest = now.minus(grace).toEpochMilli();
    for (Attachments.Attachment file : accounts.attachments.all(Attachments.CEILING)) {
      if (referenced.contains(file.id())) {
        continue;
      }
      if (file.createdAt() != null && file.createdAt().getTime() > youngest) {
        // uploaded in the last day: very likely on somebody's clipboard right now, on its way into
        // a page that does not exist yet
        continue;
      }
      unused.add(file);
      freeable += file.bytes();
    }
    return new Result(referenced, uses, unused, sources, problems, rows, freeable, now);
  }

  private static void mark(String text, String source, String where, Set<Long> referenced,
                           List<Use> uses) {
    if (text == null || text.isEmpty()) {
      return;
    }
    Matcher matcher = REFERENCE.matcher(text);
    while (matcher.find()) {
      try {
        long id = Long.parseLong(matcher.group(1));
        if (referenced.add(id) || uses.size() < 5000) {
          uses.add(new Use(id, source, where));
        }
      } catch (NumberFormatException ex) {
        // an id longer than a long is not an id this server ever wrote
      }
    }
  }

  /** how many times each source pointed at something, for the report */
  public static Map<String, Integer> bySource(Result result) {
    LinkedHashMap<String, Integer> counts = new LinkedHashMap<>();
    for (Use use : result.uses()) {
      counts.merge(use.source(), 1, Integer::sum);
    }
    return counts;
  }
}
